---
- name: Testing Website Playbook
  connection: local
  hosts: localhost
  tasks:
    - block:
      - name: Connect with the webpage and save results
        action: uri url=http://ec2-18-184-249-8.eu-central-1.compute.amazonaws.com/ return_content=yes
        register: webpage

    - block:
        - name: Create log with the issue
          lineinfile:
            create: yes
            line: "{{ lookup('pipe','date') }} Web contents have been changed an webpage is not working as expected"
            insertafter: EOF
            dest: "/home/errorlog.txt"
      when: "'Welcome to NASA Astronomy Picture of the Day' not in webpage.content"
