---
- name: Testing Website Playbook
  connection: local
  hosts: localhost
  tasks:
    - action: uri url=http://ec2-18-184-249-8.eu-central-1.compute.amazonaws.com/ return_content=yes
      register: webpage

    - block:
        - name: Create log with the issue
          copy:
            dest: "/home/jenkins/errorlog__{{ lookup('pipe','date +%y_%m_%d') }}.txt"
            content: |
               {{ lookup('pipe','date') }} A file has been uploaded an webpage is not working properly
          become: yes
      when: "'Welcome to NASA Astronomy Picture of the Day' not in webpage.content"

    - fail:
        msg: 'service is not happy'
      when: "'Welcomex to NASA Astronomy Picture of the Day' not in webpage.content"
